check50:
  dependencies:
    - flask_session
  files: &check50_files
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !exclude venv
    - !require app.py
    - !require finance.db
    - !require helpers.py

submit50:
  files: *check50_files
